// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package mmopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BroadCastType int32

const (
	BroadCastType_Unspecified   BroadCastType = 0
	BroadCastType_World_Chat    BroadCastType = 1
	BroadCastType_Player_Pos    BroadCastType = 2
	BroadCastType_Player_Action BroadCastType = 3
	BroadCastType_After_Move    BroadCastType = 4
)

var BroadCastType_name = map[int32]string{
	0: "Unspecified",
	1: "World_Chat",
	2: "Player_Pos",
	3: "Player_Action",
	4: "After_Move",
}

var BroadCastType_value = map[string]int32{
	"Unspecified":   0,
	"World_Chat":    1,
	"Player_Pos":    2,
	"Player_Action": 3,
	"After_Move":    4,
}

func (x BroadCastType) String() string {
	return proto.EnumName(BroadCastType_name, int32(x))
}

func (BroadCastType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

// 同步客户端玩家id
type SyncPlayerId struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPlayerId) Reset()         { *m = SyncPlayerId{} }
func (m *SyncPlayerId) String() string { return proto.CompactTextString(m) }
func (*SyncPlayerId) ProtoMessage()    {}
func (*SyncPlayerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SyncPlayerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPlayerId.Unmarshal(m, b)
}
func (m *SyncPlayerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPlayerId.Marshal(b, m, deterministic)
}
func (m *SyncPlayerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPlayerId.Merge(m, src)
}
func (m *SyncPlayerId) XXX_Size() int {
	return xxx_messageInfo_SyncPlayerId.Size(m)
}
func (m *SyncPlayerId) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPlayerId.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPlayerId proto.InternalMessageInfo

func (m *SyncPlayerId) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 玩家位置
type Position struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	V                    float32  `protobuf:"fixed32,4,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Position) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Position) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

// 玩家广播数据
type BroadCast struct {
	PlayerId int32         `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Type     BroadCastType `protobuf:"varint,2,opt,name=type,proto3,enum=mmopb.BroadCastType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*BroadCast_Content
	//	*BroadCast_Pos
	//	*BroadCast_Action
	Data                 isBroadCast_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BroadCast) Reset()         { *m = BroadCast{} }
func (m *BroadCast) String() string { return proto.CompactTextString(m) }
func (*BroadCast) ProtoMessage()    {}
func (*BroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *BroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadCast.Unmarshal(m, b)
}
func (m *BroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadCast.Marshal(b, m, deterministic)
}
func (m *BroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadCast.Merge(m, src)
}
func (m *BroadCast) XXX_Size() int {
	return xxx_messageInfo_BroadCast.Size(m)
}
func (m *BroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_BroadCast proto.InternalMessageInfo

func (m *BroadCast) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *BroadCast) GetType() BroadCastType {
	if m != nil {
		return m.Type
	}
	return BroadCastType_Unspecified
}

type isBroadCast_Data interface {
	isBroadCast_Data()
}

type BroadCast_Content struct {
	Content string `protobuf:"bytes,3,opt,name=content,proto3,oneof"`
}

type BroadCast_Pos struct {
	Pos *Position `protobuf:"bytes,4,opt,name=pos,proto3,oneof"`
}

type BroadCast_Action struct {
	Action int32 `protobuf:"varint,5,opt,name=action,proto3,oneof"`
}

func (*BroadCast_Content) isBroadCast_Data() {}

func (*BroadCast_Pos) isBroadCast_Data() {}

func (*BroadCast_Action) isBroadCast_Data() {}

func (m *BroadCast) GetData() isBroadCast_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BroadCast) GetContent() string {
	if x, ok := m.GetData().(*BroadCast_Content); ok {
		return x.Content
	}
	return ""
}

func (m *BroadCast) GetPos() *Position {
	if x, ok := m.GetData().(*BroadCast_Pos); ok {
		return x.Pos
	}
	return nil
}

func (m *BroadCast) GetAction() int32 {
	if x, ok := m.GetData().(*BroadCast_Action); ok {
		return x.Action
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BroadCast) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BroadCast_Content)(nil),
		(*BroadCast_Pos)(nil),
		(*BroadCast_Action)(nil),
	}
}

// 玩家聊天数据
type Talk struct {
	TargetPlayerId       int32    `protobuf:"varint,1,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Talk) Reset()         { *m = Talk{} }
func (m *Talk) String() string { return proto.CompactTextString(m) }
func (*Talk) ProtoMessage()    {}
func (*Talk) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Talk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Talk.Unmarshal(m, b)
}
func (m *Talk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Talk.Marshal(b, m, deterministic)
}
func (m *Talk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Talk.Merge(m, src)
}
func (m *Talk) XXX_Size() int {
	return xxx_messageInfo_Talk.Size(m)
}
func (m *Talk) XXX_DiscardUnknown() {
	xxx_messageInfo_Talk.DiscardUnknown(m)
}

var xxx_messageInfo_Talk proto.InternalMessageInfo

func (m *Talk) GetTargetPlayerId() int32 {
	if m != nil {
		return m.TargetPlayerId
	}
	return 0
}

func (m *Talk) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 玩家信息
type Player struct {
	PlayerId             int32     `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Pos                  *Position `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

// 同步玩家显示数据
type SyncPlayers struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SyncPlayers) Reset()         { *m = SyncPlayers{} }
func (m *SyncPlayers) String() string { return proto.CompactTextString(m) }
func (*SyncPlayers) ProtoMessage()    {}
func (*SyncPlayers) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *SyncPlayers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPlayers.Unmarshal(m, b)
}
func (m *SyncPlayers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPlayers.Marshal(b, m, deterministic)
}
func (m *SyncPlayers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPlayers.Merge(m, src)
}
func (m *SyncPlayers) XXX_Size() int {
	return xxx_messageInfo_SyncPlayers.Size(m)
}
func (m *SyncPlayers) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPlayers.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPlayers proto.InternalMessageInfo

func (m *SyncPlayers) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterEnum("mmopb.BroadCastType", BroadCastType_name, BroadCastType_value)
	proto.RegisterType((*SyncPlayerId)(nil), "mmopb.SyncPlayerId")
	proto.RegisterType((*Position)(nil), "mmopb.Position")
	proto.RegisterType((*BroadCast)(nil), "mmopb.BroadCast")
	proto.RegisterType((*Talk)(nil), "mmopb.Talk")
	proto.RegisterType((*Player)(nil), "mmopb.Player")
	proto.RegisterType((*SyncPlayers)(nil), "mmopb.SyncPlayers")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0xae, 0xd2, 0x40,
	0x14, 0x80, 0xfb, 0x47, 0xef, 0xed, 0xe9, 0x2d, 0xd4, 0x89, 0x8b, 0x89, 0x6e, 0xb0, 0x2e, 0x6c,
	0x34, 0x61, 0x81, 0x89, 0x7b, 0xc0, 0x45, 0x35, 0x31, 0x21, 0x15, 0xe3, 0xb2, 0x19, 0xda, 0x01,
	0x1b, 0xa1, 0x33, 0xe9, 0x4c, 0x08, 0xe5, 0xbd, 0x7c, 0x3f, 0x33, 0x33, 0x2d, 0x44, 0x73, 0xc3,
	0x8e, 0xef, 0xfc, 0xcd, 0x77, 0x0e, 0x85, 0xe8, 0x48, 0x85, 0x20, 0x7b, 0x3a, 0xe3, 0x2d, 0x93,
	0x0c, 0x8d, 0x8e, 0x47, 0xc6, 0xb7, 0xc9, 0x07, 0x78, 0xfa, 0xde, 0x35, 0xe5, 0xfa, 0x40, 0x3a,
	0xda, 0x7e, 0xa9, 0xd0, 0x6b, 0x08, 0xb8, 0xfe, 0x5d, 0xd4, 0x15, 0xb6, 0xa7, 0x76, 0x3a, 0xca,
	0x1f, 0x79, 0x9f, 0x4c, 0x96, 0xf0, 0xb8, 0x66, 0xa2, 0x96, 0x35, 0x6b, 0xd0, 0x13, 0xd8, 0x67,
	0x5d, 0xe0, 0xe4, 0xf6, 0x59, 0x51, 0x87, 0x1d, 0x43, 0x9d, 0xa2, 0x0b, 0x76, 0x0d, 0x5d, 0x14,
	0x9d, 0xb0, 0x67, 0xe8, 0x94, 0xfc, 0xb1, 0x21, 0x58, 0xb6, 0x8c, 0x54, 0x2b, 0x22, 0xe4, 0xdd,
	0xe7, 0x50, 0x0a, 0x9e, 0xec, 0x38, 0xd5, 0x73, 0xc7, 0xf3, 0x97, 0x33, 0x6d, 0x3c, 0xbb, 0x36,
	0x6f, 0x3a, 0x4e, 0x73, 0x5d, 0x81, 0x5e, 0xc1, 0x43, 0xc9, 0x1a, 0x49, 0x1b, 0xa9, 0x9f, 0x0d,
	0x32, 0x2b, 0x1f, 0x02, 0xe8, 0x2d, 0xb8, 0x9c, 0x09, 0x2d, 0x10, 0xce, 0x27, 0xfd, 0x90, 0x61,
	0x8d, 0xcc, 0xca, 0x55, 0x16, 0x61, 0xf0, 0x49, 0xa9, 0x02, 0x78, 0xa4, 0x24, 0x32, 0x2b, 0xef,
	0x79, 0xe9, 0x83, 0xf7, 0x99, 0x48, 0x92, 0x7c, 0x05, 0x6f, 0x43, 0x0e, 0xbf, 0x51, 0x0a, 0xb1,
	0x24, 0xed, 0x9e, 0xca, 0xe2, 0x7f, 0xf1, 0xb1, 0x89, 0x5f, 0x4f, 0x89, 0x6f, 0x52, 0x6a, 0x83,
	0xe0, 0xaa, 0x94, 0x64, 0xe0, 0x9b, 0xaa, 0xfb, 0xfb, 0xbf, 0x31, 0xe6, 0xce, 0xb3, 0xe6, 0xda,
	0x3b, 0xf9, 0x04, 0xe1, 0xed, 0xef, 0x13, 0xe8, 0x1d, 0x3c, 0x98, 0x6e, 0x81, 0xed, 0xa9, 0x9b,
	0x86, 0xf3, 0x68, 0xe8, 0xd2, 0xd1, 0x7c, 0xc8, 0xbe, 0x2f, 0x21, 0xfa, 0xe7, 0x8e, 0x68, 0x02,
	0xe1, 0x8f, 0x46, 0x70, 0x5a, 0xd6, 0xbb, 0x9a, 0x56, 0xb1, 0x85, 0xc6, 0x00, 0x3f, 0x59, 0x7b,
	0xa8, 0x8a, 0xd5, 0x2f, 0x22, 0x63, 0x5b, 0xb1, 0x19, 0x52, 0xac, 0x99, 0x88, 0x1d, 0xf4, 0x02,
	0xa2, 0x9e, 0x17, 0xfa, 0x50, 0xb1, 0xab, 0x4a, 0x16, 0x3b, 0x49, 0xdb, 0xe2, 0x1b, 0x3b, 0xd1,
	0xd8, 0xdb, 0xfa, 0xfa, 0x4b, 0xfb, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0xed, 0xd4, 0x52, 0x76,
	0x7a, 0x02, 0x00, 0x00,
}
